### ISSUE TITLE
Draft Simple Dash App

### ISSUE THREAD

**Issue by pmaji** [pmaji/asset-time-machine-app#17]
Here is an issue we can use to track progress and conversation surrounding the 1st draft of the Dash App. Once we have the data wrangled, the all-time-high algorithm locked down, and a visualization ready to go, we'll want to start probably with a one-callback dash app that runs decently fast. We can then of course moving on to more callbacks, deeper interactivity, etc., but for that we can open a separate issue and build towards a different milestone.

**Comment by pmaji** [comment]
Link to Dash tutorial here, for reference:

https://dash.plot.ly/

**Comment by pmaji** [comment]
We'll get started on this next @zachvac -- feel free to begin drafting the dash app.py file itself, as I am close to finishing up all the prep code (see post under other issue) and should have the viz locked down shortly.

**Comment by pmaji** [comment]
Pursuant to my comment over on the other issue @zachvac, the visual is now done, the explore.ipynb is fully optimized, and we are good to start on the app. Be sure the virtual env, requirements.txt, etc. is working for you, as discussed, and then we'll start on the app.py!

**Comment by pmaji** [comment]
![Screen Shot 2019-07-06 at 2 17 01 PM](https://user-images.githubusercontent.com/25461122/60759797-c954e280-9ff8-11e9-83a2-f234f7ca4371.jpg)

Kudos to @zachvac for getting the first version of this puppy up and running! I've put a screenshot of the first stage here to track iteration. I am really impressed with how sleek it looks and how it fast it runs off the rip!

To log my thoughts, there are a few things I'm pondering (and I know @zachvac mentioned he had a few areas for improvement he wanted to work on tomorrow as well).

- I can't decide if I want to start by showing the full chart, or show some zoomed in view as I do with the 1-year default in the explore.ipynb. Either way, I like the default of pulling all data since 2000--although we'll probably want to make that a parameterized callback eventually. 
- The buttons for 1YR, 2YR, etc. are oddly bolder than the were showing up in the explore.ipynb. Not sure if that's a CSS issue, or what. 
- We'll want a title, link to GitHub, etc., and other basic CSS stuff. 

This is looking SWEET!

**Comment by pmaji** [comment]
I put this comment over under my most recent pull request as well @zachvac, but thought I would put the update here as well if it's more convenient to get to (still not exactly sure when / if you get notifications on here). 

In my must recent PR I did include the addition of my version of the app.py to master, even though it's not in a great place right now. Feel free to ignore my app.py, and keep working out of your own (the one I added is just your version that I copy-pasted locally last night, with the one difference being that I swapped out the old yahoo finance package name for yfinance. We'll just overwrite the app.py in master whenever you make your improvements. **What I wanted to take care of was the requirements.txt, which is now good to go!** So feel free to re-pull / merge master to ensure you're using the right package versions. I had missed a few.

Also, if you are using Jupyter lab or noteboks, you'll want to have a look at the mini section I added to the README now that describes how to ensure that when you open a notebook or lab session you're calling the session using only the packages / versions from the virtual environment. I've pasted that below as well.

**To get started working on this project using jupyter lab:**

- ensure you have your virtual env set up as described above
- ensure that you install all the requisite packages using the aforementioned 'pip install -r requirements.txt'
- start your jupyter lab session with 'env/bin/jupyter-lab'
- ensure that the name of the kernel that starts in your terminal matches the kernel listed in the top right of your jupyter lab session

Won't be doing anything else on this today I don't think, but glad to see where we're headed!

**Comment by zachvac** [comment]
Here are the things I'm going to try to work on tomorrow:

ticker list
enter key works
adding crypto
research deploying dash in production (multithreading?)

**Comment by pmaji** [comment]
Sweet! Looking forward to seeing what you discover. My next step will be to do a solid QC / format / factor check, etc. of the app.py code. I'll also do a little research into how we can make the aesthetics of the app a little nicer. Historically I've either used Dash presets or had to resort to using injected javascript / html, so we'll see about that. Don't plan on getting to much in terms of pushed code today or tomorrow however due to travel.

**Comment by zachvac** [comment]
Sorry been busy the last few weeks, did some work tonight. Got the list here: https://www.nasdaq.com/etfs/list

and that worked to have a list of securities although it's clearly not comprehensive. Let me know if you have a better list and I'll point to that. I feel like you texted me something but it was too long ago.

**Comment by pmaji** [comment]
@zachvac I think the one I was thinking of (for individual stocks -- so we would want to add to your ETF list) is here. There's a csv link that we can point to

https://www.nasdaq.com/screening/companies-by-industry.aspx?exchange=NYSE

**Comment by pmaji** [comment]
@zachvac -- following up on the above, I didn't see the ETF list integration anywhere in master, so I assume that's in your local branch. Whenever you push those changes to master lemme know! Did a few things today that might be helpful:

- found the list of all stocks linked above; I think that list (when combined with your ETF list) should give us everything we need in terms of covering all assets folks could reasonably want.
- once you integrate the asset lists into master, then we'll want to implement the searchable drop-down list we discussed on the call instead of the plain text entry we have right now. that should eliminate the need for the error handling try / catch logic we have been struggling to implement. 
- I also did a bunch of research this a.m. to round out my understanding of environments. I think I finally understand the full utility of the envs from start to finish, and have added some code to the readme that shows how to ensure that you're using the jupyter lab version I specify in the requirements.txt -- `env/bin/jupyter-lab` -- as well as how to ensure you're running the app using the python version I specified in the requirements.txt -- `env/bin/python3 app.py`. 
- I made a few other small changes and started adding some comments to the `app.py` code, and also changed the default asset in the app to be VTI so that it's more broadly applicable when we start sharing this thing haha. 

Let me know if you have questions about any of the above / need help with anything. I figure the next stages in my mind are (kind of in order but not really):

- you integrate the two asset lists and push to master
- we integrate the new text search / drop-down combo dash html widget in place of the plain text
- add a bit more aesthetic detail (title for the app, maybe a link to the github)
- clean up the code / comment extensively
- write up a more formal readme with the basic use case and better illustrations (I'd like to take care of this as I think I've gotten pretty decent at this kinda doc from my other repos)
- begin sharing first drafts of the app on different sites (twitter / reddit / etc.)
- look to integrate crypto as well
- build out the table to put below the charts of previous points in history where asset X was also down this far from all time high
- anything else you think of

**Comment by pmaji** [comment]
Two other updates to add to the above--one new, one which I stupidly forgot--that should be tacked on to our to-do list.

- I forgot this, but we need to remember to add a callback so folks can specify the date from which they want to measure the all-time high. I think we can default to showing like 2000 on with a zoom-in by default to like the past few years, but the API goes back farther so we should give users that option. As such, we'll wind up with 2 callbacks: a drop-down search menu for the asset, and a datetime selector to pick the measurement start date. 
- @zachvac -- Andrew Gele (@ndrewGele) shared something really cool he cooked up recently with me today. It's some python code that hits yahoo's API and sends you an email or text whenever that stock is in a certain 52 week range (low? I think?). Anywho, that got me we think we can maybe combine forces and in a future iteration of the app build it out so folks can subscribe to notificatins. This is definitely a way-down-the-road kind of thing, but I wanted to [share the repo here](https://github.com/ndrewGele/yf_alerts) so we can start the conversation!

**Comment by pmaji** [comment]
@zachvac I fixed the environment in master so now you don't have to worry about pip commands or any `env` nested directories. Just two simple conda commands and you're good to go. Check it out when you can, and let me know your thoughts on my previous posts above in this issue so we can keep making progress.

**Comment by ndrewGele** [comment]
Having trouble setting up the environment based on the yaml. Here's a thread with the same issue I'm having: [https://github.com/ContinuumIO/anaconda-issues/issues/9480](https://github.com/ContinuumIO/anaconda-issues/issues/9480)
It looks like part of the solution is to specify `--no-builds` when you create the yaml (not sure if you did this or not already).

**Comment by pmaji** [comment]
@zachvac all I want for Christmas is for you to respond to my message and merge your changes to master lol.
