### ISSUE TITLE
Environment creation and management 

### ISSUE THREAD

**Issue by pmaji** [pmaji/asset-time-machine-app#31]
Starting this issue to migrate conversation about environment-related issues. @ndrewGele -- deleting your comment over in the main app dev issue thread and pasting it below because I think it merits a full thread. 

From @ndrewGele

"Having trouble setting up the environment based on the yaml. Here's a thread with the same issue I'm having: ContinuumIO/anaconda-issues#9480
It looks like part of the solution is to specify --no-builds when you create the yaml (not sure if you did this or not already)."

**Comment by pmaji** [comment]
@zachvac I fixed the environment in master so now you don't have to worry about pip commands or any env nested directories. Just two simple conda commands and you're good to go. Check it out when you can, and let me know your thoughts on my previous posts above in the other main issue so we can keep making progress.

**Comment by pmaji** [comment]
@ndrewGele -- repull from master and try now? I recreated the .yml using the prefix you suggested. I also read the rest of the thread and it seems like there are a few other solutions I would try.

1 - be sure your conda is fully up to date with a conda update call
2 - if that doesn't work it appears to be because of an incongruence between versions of packages you have locally versus those in the channels specified in the yaml, and so that means either hunting for the local ones to update them, or moving all the packages under "pip" in your local .yml, as that supposedly will work

I hope it works now for you! Lemme know how I can help if otherwise.

**Comment by pmaji** [comment]
PS @ndrewGele -- I just went through and did a full reinstall of the env in a fresh directory with nothing but the .yml file and that worked, so I'm hoping that's a good sign and that it was jus the conda update issue or that your `no build` solution worked its magic. Thanks for calling this out!

**Comment by ndrewGele** [comment]
Yeah I did a full conda update first hoping that would do the trick.
I'll give it another shot soon!

**Comment by ndrewGele** [comment]
This definitely helped, but there are still a few offenders. Having Google'd a few of them, it looks like these aren't compatible with (and probably aren't meant for) Windows systems. If they're just dependencies, removing them might work, so I'm going to give that a try. If that doesn't work, you might need OS-specific yamls. Will update tomorrow probably.
1. libcxxabi=9.0.0
2. libuv=1.32.0
3. libgfortran=4.0.0
4. appnope=0.1.0
5. ncurses=6.1
6. libcxx=9.0.0
7. readline=8.0

**Comment by pmaji** [comment]
@ndrewGele thank you sir! One other idea -- you might have already tried this -- would be once you know all of the packages that you think aren't needed / are PC-breaking but OS-specific, moving them under the pip: section might work. At least, this link seems to intimate that that will fix the problem (because it'd be great not to have to have two yamls, and this might solve for that). https://stackoverflow.com/questions/49154899/resolvepackagenotfound-create-env-using-conda-and-yml-file-on-macos
